### PR TITLE
Feature/split jsons

### PR DESCRIPTION
**Pull request by cjbacchus**
This branch splits up the data to be transferred into several properly-formed json files, rather than one large .js file. The server generates these jsons when requested by the client, and not before. The server also now generates the image files on-demand rather than up-front. The result of all this is that navigation between events is substantially faster.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
The CI results are normal.

**Comment by absolution1** [comment]
approve

**Comment by aihimmel** [comment]
Approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
