### PR TITLE
No longer require a temporary directory

### PR DESCRIPTION
**Pull request by cjbacchus**
No longer require a temporary directory. coords.js is now served directly from memory, and it and the various static files are compressed on-demand.

### CODE REVIEW

**Comment by cjbacchus** [comment]
This is on top of feature/lazy_png. I thought I could rebase it, but lazy_png isn't actually merged to develop until just before the release? So I guess we go ahead like this.

**Comment by cjbacchus** [comment]
trigger build

**Comment by lgarren** [comment]
@cjbackhouse lazy png has been merged with develop.   If you are working from a fork, you have to pull upstream.

**Comment by knoepfel** [comment]
No coding issues worth flagging.  Should receive approval when CI tests come back normal.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
CI results are normal

**Comment by lgarren** [comment]
approve

**Pull request merged**
