### PR TITLE
Feature/adc traces

### LINKED ISSUE #9: Ability to display entire 1D waveform for a channel
Requested by Dom

### PR DESCRIPTION
**Pull request by cjbacchus**
Adds a mode that shows RawDigit and recob::Wires as a time series.

This branch also has feature/localStorage merged into it and should be pulled after that PR is complete.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
@cjbackhouse  After merging the other webevd PRs, this PR has conflicts.  It's a single line.  Please check and resolve.

**Comment by cjbacchus** [comment]
@lgarren done

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@cjbackhouse  The build has failed.  Please see the log. https://dbweb8.fnal.gov:8443/LarCI/app/storage/docs/2021/02/11/buildLArSoft.log

**Comment by cjbacchus** [comment]
OK, this is a conflict with the feature/getInputTags branch. This is what I get for having so many in flight at once. It's an easy fix though. Give me a minute...

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@cjbackhouse The c7 build has failed with an unused variable.  It looks like it is meant to be used... :(

**Comment by cjbacchus** [comment]
In fact it is unused. The exact same thing is passed directly to a function call on the next line. I pushed the fix. Third time's the charm?

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
